### ISSUE TITLE
smokeping not start Smokeping::probes::WifiParams failed

### ISSUE THREAD

**Issue by ma3s7ro** [mad-ady/smokeping-wifi-param#2]
Hello, 
Could you help me with WifiParam.pm?

If I add it to /usr/share/perl5/Smokeping/probes/
I have error from systemctl:
`require/Smokeping::probes::WifiParams failed: Can't locate Smokeping/probes/WifiParams.pm`

I try reaname file WifiParam.pm to WifiParams.pm but then I have another error:
`Can't locate object method "probevars" via package "Smokeping::probes::WifiParams" at /usr/share/perl5/Smokeping.pm line 2481, <$fh> line 58.`

Configuration in Probes
+ WifiParams
binary = /sbin/iw
pings = 3
step = 300
offset = random

++ WifiParamsWlan0
interface = wlan0

+++ WifiParamsWlan0Freq
parameter = freq

+++ WifiParamsWlan0Signal
parameter = signal

+++ WifiParamsWlan0Bitrate
parameter = bitrate

++ WifiParamsWlan1
interface = wlan1

+++ WifiParamsWlan1Freq
parameter = freq

+++ WifiParamsWlan1Signal
parameter = signal

+++ WifiParamsWlan1Bitrate
parameter = bitrate

Best regards.

**Comment by mad-ady** [comment]
The file is called `WifiParam.pm` and the configuration section should be called `WifiParam` as well, not `WifiParams` as stated in the example. I corrected the documentation.

**Comment by ma3s7ro** [comment]
Erorr with Section WifiParam 
ERROR: /etc/smokeping/config.d/Probes, line 67: no sections are allowed

line 67 is
+++ WifiParamsWlan0Freq

**Comment by mad-ady** [comment]
Can you post the Probes file on pastebin and share a link?

**Comment by ma3s7ro** [comment]
Done
Please check it
https://pastebin.com/2c7kBwp5

**Comment by mad-ady** [comment]
Hmm, I don't remember exactly how I used to use it... Can you try this
instead of nested levels?
```
++ WifiParamsWlan0
interface = wlan0

++ WifiParamsWlan0Freq
interface = wlan0
parameter = freq

++ WifiParamsWlan0Signal
interface = wlan0
parameter = signal

++ WifiParamsWlan0Bitrate
interface = wlan0
parameter = bitrate
```
Let me know if this works.

**Comment by ma3s7ro** [comment]
Hm it is working. But need more info about Target. 
ERROR: /etc/smokeping/config.d/Targets, line 125: probe WifiParam missing from the Probes section

+ Wi-Fi
menu = Wi-Fi
title = Wi-Fi

++ wifi-freq
menu = Wifi_Parameters
title = Wifi_Parameters
probe = WifiParam
interface = wlan0 - interface which I use
parameter = freq (As I understand I can change it to freq/signal/bitrate)
host = 192.168.1.8 - current host
slaves = 192.168.1.1 - router to which I want check connection.

Correct? or I'm wrong?

**Comment by mad-ady** [comment]
Not sure why you are getting `line 125: probe WifiParam missing from the
Probes section`.

Regarding your target setup, here's one of my old examples:
```
+++ IQ-01-wifi_-_freq
menu = Wifi Parameters IQ-01-wifi freq
title = Wifi Parameters IQ-01-wifi freq
probe = WifiParam
interface = wlan0
parameter = freq
host = dummy.com
slaves = IQ-01-wifi

+++ IQ-01-wifi_-_signal
menu = Wifi Parameters IQ-01-wifi signal
title = Wifi Parameters IQ-01-wifi signal
probe = WifiParam
interface = wlan0
parameter = signal
host = dummy.com
slaves = IQ-01-wifi

+++ IQ-01-wifi_-_bitrate
menu = Wifi Parameters IQ-01-wifi bitrate
title = Wifi Parameters IQ-01-wifi bitrate
probe = WifiParam
interface = wlan0
parameter = bitrate
host = dummy.com
slaves = IQ-01-wifi
```

Parameter can be bitrate/signal/freq, host needs to be set, but it's not
used (can be anything), slaves - is the slave name in case you're running a
master/slave smokeping setup. Otherwise don't add it for a standalone setup.
Note that the plugin measures wifi parameters only on the local (or slave)
machine. So if you want wifi params for your router, you'll need to run
smokeping (either standalone or as a slave) on your router.
Note 2 - I haven't actually used the plugin much. I only did some
preliminary tests with it. So some things might be broken.

**Comment by ma3s7ro** [comment]
Ok thanks a lot. I will test it)
